image: emeris/rpcwatcher:latest
imagePullPolicy: Always

replicas: 1

nodeSelector: {}

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

ports:
  http: 8000

databaseConnectionURL: postgres://root@cockroachdb-public:26257?sslmode=disable

debug: true

apiUrl: api-server:8000

redisUrl: redis-master:6379