# TOML Document

title = "TOML Document"


# http ,https
ssl_mode = "false"

# if mode dev null
ssl_crt = "./server.crt"
ssl_key = "./server.key"

# 127.0.0.1:8000
rest_ip_port = "127.0.0.1:9999"

# Api Subscription Interval
Interval = 10

#"postgres://{username}:{password}@{hostname}:{port}/bank?sslmode=require"
db = "postgres://testuser:qwer1234@127.0.0.1:26257/oracle?sslmode=require"
coinmarketcap_key =""
whitelist_tokens = ["ATOMUSDT","LUNAUSDT","ETHUSDT"]
whitelist_fiats = ["",]
[APIs]
        [APIs.Atom.Usd]
        binance = "https://api.binance.com/api/v3/ticker/price"
        coinmarketcap = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"
        [APIs.Stables]
        # API key is required
        # https://currencylayer.com/product
        currencylayer = "https://api.currencylayer.com/live?access_key="

        [APIs.band]
        active = true
        band = "https://terra-lcd.bandchain.org"
