# http ,https
sslmode = false

# if mode dev null
sslcrt = ""
sslkey = ""

#"postgres://{username}:{password}@{hostname}:{port}/bank?sslmode=require"
db = "postgres://testuser:qwer1234@127.0.0.1:26257/oracle?sslmode=require"

# 127.0.0.1:8000
laddr = "127.0.0.1:9999"

# Api Subscription Interval
interval = 10

whitelisttokens = ["ATOMUSDT","LUNAUSDT","ETHUSDT"]
whitelistfiats = ["USDEUR","USDKRW"]

coinmarketcapapikey =""

[APIs]
        [APIs.Atom.Usd]
        binance = "https://api.binance.com/api/v3/ticker/price"
        coinmarketcap = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"
        [APIs.Stables]
        # API key is required
        # https://currencylayer.com/product
        currencylayer = "https://api.currencylayer.com/live?access_key="

        [APIs.band]
        active = true
        band = "https://terra-lcd.bandchain.org"
