apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.labels" . | indent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: api-server
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
{{- include "ports.pod" . | indent 8 }}
          env:
            - name: RPCWATCHER_DATABASECONNECTIONURL
              value: "{{ .Values.databaseConnectionURL }}"
            - name: RPCWATCHER_DEBUG
              value: "{{ .Values.debug }}"
            - name: RPCWATCHER_REDISURL
              value: "{{ .Values.redisUrl }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: 10