apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.labels" . | indent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      nodeSelector:
  {{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: ticket-watcher
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
          {{- include "ports.pod" . | indent 8 }}
          env:
          - name: EMERIS-TW_DEBUG
            value: "{{ .Values.debug }}"
          - name: EMERIS-TW_REDISURL
            value: "{{ .Values.redisUrl }}"
          resources: { { toYaml .Values.resources | indent 12 } }
      terminationGracePeriodSeconds: 10