apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-scale-down
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: wait-for-disable-chain
        image: groundnuty/k8s-wait-for:v1.3
        imagePullPolicy: Always
        args:
        - "job"
        - "{{ .Release.Name }}-disable-chain"
      containers:
      - name: kubectl
        image: bitnami/kubectl
        {{- if .Values.skipScaleDown }}
        command: ["echo", "Do not scale down nodeset. Skipping..."]
        {{- else }}
        command: ["kubectl", "scale", "nodeset", "{{- include "targetChain" . }}", "--replicas=0", "-n", "emeris"]
        {{- end }}
      restartPolicy: Never
  backoffLimit: 0