apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-erase-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: wait-for-scale-down
        image: groundnuty/k8s-wait-for:v1.3
        imagePullPolicy: Always
        args:
        - "job"
        - "{{ .Release.Name }}-scale-down"
      - name: wait-pods-down
        image: bitnami/kubectl
        command: ["kubectl", "wait", "pod", "--selector", "nodeset={{- include "targetChain" . }}", "--for=delete", "-n", "emeris"]
      containers:
      - name: resetchain
        image: "gcr.io/tendermint-dev/emeris-tracelistener-resetchain:main"
        args:
        - -chain
        - "{{- include "targetChain" . }}"
        - -db
        - postgresql://root@cockroachdb-public:26257/tracelistener?sslmode=disable
      restartPolicy: Never
  backoffLimit: 0
