apiVersion: batch/v1
kind: Job
metadata:
  name: 02-{{ .Release.Name }}-erase-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: wait-for-scale-down
        image: groundnuty/k8s-wait-for:v1.3
        imagePullPolicy: Always
        args:
        - "job"
        - "01-{{ .Release.Name }}-scale-down"
      containers:
      - name: cockroach-client
        image: "cockroachdb/cockroach:v21.2.5"
        args:
        - sql
        - --insecure
        - --host=cockroachdb-public
        - --database=tracelistener
        - -e
        - DELETE FROM tracelistener.balances WHERE chain_name='{{- include "targetChain" . }}';
          DELETE FROM tracelistener.connections WHERE chain_name='{{- include "targetChain" . }}';
          DELETE FROM tracelistener.delegations WHERE chain_name='{{- include "targetChain" . }}';
          DELETE FROM tracelistener.unbonding_delegations WHERE chain_name='{{- include "targetChain" . }}';
          DELETE FROM tracelistener.denom_traces WHERE chain_name='{{- include "targetChain" . }}';
          DELETE FROM tracelistener.channels WHERE chain_name='{{- include "targetChain" . }}';
          DELETE FROM tracelistener.auth WHERE chain_name='{{- include "targetChain" . }}';
          DELETE FROM tracelistener.clients WHERE chain_name='{{- include "targetChain" . }}';
          DELETE FROM tracelistener.validators WHERE chain_name='{{- include "targetChain" . }}';
      restartPolicy: Never
  backoffLimit: 0