apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-reimport-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "{{- include "targetChain" . }}-{{ .Values.useDisk }}"
      initContainers:
      - name: wait-for-erase-data
        image: groundnuty/k8s-wait-for:v1.3
        imagePullPolicy: Always
        args:
        - "job"
        - "{{ .Release.Name }}-erase-data"
      containers:
      - name: tracelistener
        image: "{{- if eq .Values.sdkVersion "0.44" }}{{ printf "%s:%s" .Values.traceListener44Image .Values.traceListenerVersion }}{{- else }}{{ printf "%s:%s" .Values.traceListener42Image .Values.traceListenerVersion }}{{ end }}"
        imagePullPolicy: Always
        args: ["-import", "/home/nonroot/data/application.db"]
        env:
        - name: TRACELISTENER_DATABASECONNECTIONURL
          value: postgres://root@cockroachdb-public:26257?sslmode=disable
        - name: TRACELISTENER_TYPE
          value: gaia
        - name: TRACELISTENER_CHAINNAME
          value: "{{- include "targetChain" . }}"
        volumeMounts:
        - mountPath: /home/nonroot/data
          name: data
      restartPolicy: Never
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
  backoffLimit: 0