apiVersion: batch/v1
kind: Job
metadata:
  name: 04-{{ .Release.Name }}-scale-up
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: wait-for-reimport-data
        image: groundnuty/k8s-wait-for:v1.3
        imagePullPolicy: Always
        args:
        - "job"
        - "03-{{ .Release.Name }}-reimport-data"
      containers:
      - name: kubectl
        image: bitnami/kubectl
        command: ["kubectl", "apply", "-f", "/tmp/chains/nodeset.yaml", "-n", "emeris"]
        volumeMounts:
          - name: tmp
            mountPath: /tmp/chains
      restartPolicy: Never
      volumes:
      - name: tmp
        configMap:
          name: {{ .Release.Name }}
          items:
          - key: nodeset.yaml
            path: nodeset.yaml
  backoffLimit: 0