{{- if .Values.enableChain }}
apiVersion: batch/v1
kind: Job
metadata:
  name: 05-{{ .Release.Name }}-enable-chain
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: wait-for-scale-up
        image: groundnuty/k8s-wait-for:v1.3
        imagePullPolicy: Always
        args:
        - "job"
        - "04-{{ .Release.Name }}-scale-up"
      - name: wait-for-nodes-ready
        image: groundnuty/k8s-wait-for:v1.3
        imagePullPolicy: Always
        args:
        - "pod"
        - "-lnodeset={{- include "targetChain" . }}"
      containers:
      - name: cockroach-client
        image: "cockroachdb/cockroach:v21.2.5"
        args:
        - sql
        - --insecure
        - --host=cockroachdb-public
        - --database=cns
        - -e
        - UPDATE cns.chains SET enabled = true WHERE chain_name = '{{- include "targetChain" . }}';
      restartPolicy: Never
  backoffLimit: 0
{{- end }}