apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: ixo
  namespace: emeris
spec:
  app:
    name: ixo
  image:
    build:
      repository: https://github.com/ixofoundation/ixo-blockchain.git
    name: gcr.io/tendermint-dev/ixo
    version: v1.6.0
  join:
    genesis:
      url: https://raw.githubusercontent.com/ixofoundation/genesis/master/impacthub-3/genesis.json
    persistentPeers:
      - id: cbe8c6a5a77f861db8edb1426b734f2cf1fa4020
        address: 18.166.133.210
        port: 26656
      - id: 36e4738c7efcf353d3048e5e6073406d045bae9d
        address: 80.64.208.42
        port: 26656
      - id: f0d4546fa5e0c2d84a4244def186b9da3c12ba1a
        address: 46.166.138.214
        port: 26656
      - id: c95af93f0386f8e19e65997262c9f874d1901dc5
        address: 18.163.242.188
        port: 26656
  moniker: emeris
  persistence:
    autoResize:
      enabled: true
      increment: 5G
      threshold: 80
    size: 100Gi
    storageClass: premium-rwo
  replicas: 2
  resources:
    restServer: {}
    sentry:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 4Gi
    validator: {}
  sdkVersion: stargate
