apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: cosmos-hub
  namespace: emeris
spec:
  app:
    cliName: gaiad
    daemonName: gaiad
    name: cosmos-hub
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 20s
      crisisSkipAssertInvariants: false
      startupTimeout: 30m
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: cosmos-hub
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener44:main
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: gcr.io/tendermint-dev/gaia
    version: v6.0.3
  init:
    assets:
      - 10000000000000000000000uatom
    bondDenom: uatom
    chainID: cosmos-hub-testnet
    faucet:
      creditAmount: 10000000
      denoms:
        - uatom
      domain: faucet.cosmos-hub-emeris.app.alpha.starport.cloud
      funds: 10000000000000000000000uatom
      legacySend: false
      maxCredit: 100000000
      replicas: 1
    stakeAmount: 1000000uatom
  moniker: emeris
  persistence:
    autoResize:
      enabled: true
      increment: 5G
      threshold: 80
    size: 15G
  replicas: 1
  resources:
    validator:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    sentry:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
  expose:
    domain: gaia.app.alpha.starport.cloud
    grpc: true
    rpc: true
    api: true
    p2p: true