apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: osmosis
  namespace: emeris
spec:
  app:
    cliName: osmosisd
    daemonName: osmosisd
    name: osmosis
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: osmosis
          - name: TRACELISTENER_DEBUG
            value: "true"
          - name: TRACELISTENER_USESQLGEN
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener-v44:v1.8.3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: gcr.io/tendermint-dev/osmosis
    version: v7.0.2
  persistence:
    autoResize:
      enabled: true
      increment: 5G
      threshold: 80
    size: 15G
  replicas: 1
  moniker: emeris
  init:
    assets:
      - 10000000000000000000uosmo
    bondDenom: uosmo
    chainID: osmosis-testnet
    faucet:
      creditAmount: 10000000
      denoms:
        - uosmo
      domain: faucet.osmosis-emeris.app.alpha.starport.cloud
      funds: 10000000000000000000000uosmo
      legacySend: false
      maxCredit: 100000000
      replicas: 1
    stakeAmount: 10000000000uosmo

  resources:
    validator:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi
    sentry:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi

  expose:
    domain: osmosis-emeris.app.alpha.starport.cloud
    grpc: true
    rpc: true
    api: true
    p2p: true