apiVersion: apps.starport.cloud/v1
kind: Relayer
metadata:
  name: relayer
  namespace: emeris
spec:
  chains:
  - accountPrefix: cosmos
    clockDrift: 1800s
    faucet: cosmos-hub-faucet
    gasAdjustment: "0.1"
    gasPrice:
      denom: uatom
      price: "0.02"
    hdPath: m/44'/118'/0'/0/0
    maxGas: 500000
    maxMsgNum: 15
    maxTxSize: 2097152
    nodeset: cosmos-hub
    rpcTimeout: 10s
    storePrefix: ibc
    trustThreshold:
      denominator: 3
      numerator: 1
    trustingPeriod: 14days
  - accountPrefix: akash
    clockDrift: 1800s
    faucet: akash-faucet
    gasAdjustment: "0.1"
    gasPrice:
      denom: uakt
      price: "0.02"
    hdPath: m/44'/118'/0'/0/0
    maxGas: 500000
    maxMsgNum: 15
    maxTxSize: 2097152
    nodeset: akash
    rpcTimeout: 10s
    storePrefix: ibc
    trustThreshold:
      denominator: 3
      numerator: 1
    trustingPeriod: 14days
  - accountPrefix: terra
    clockDrift: 1800s
    faucet: terra-faucet
    gasAdjustment: "0.1"
    gasPrice:
      denom: uluna
      price: "0.02"
    hdPath: m/44'/330'/0'/0/0
    maxGas: 500000
    maxMsgNum: 15
    maxTxSize: 2097152
    nodeset: terra
    rpcTimeout: 10s
    storePrefix: ibc
    trustThreshold:
      denominator: 3
      numerator: 1
    trustingPeriod: 14days
  clearPacketsInterval: 600
  filter: true
  logLevel: debug
  paths:
  - sideA: cosmos-hub
    sideB: terra
  - sideA: cosmos-hub
    sideB: akash
  - sideA: akash
    sideB: terra
  resources: {}
  strategy: packets
  telemetryEnabled: false
  txConfirmation: true