apiVersion: apps.starport.cloud/v1
kind: Relayer
metadata:
  name: relayer
  namespace: emeris
spec:
  filter: true

  chains:
    - nodeset: cosmos-hub
      faucet: cosmos-hub-faucet
      gasPrice:
        price: "0.001"
      accountPrefix: cosmos
      hdPath: m/44'/118'/0'/0/0

    - nodeset: akash
      faucet: akash-faucet
      gasPrice:
        price: "0.001"
      accountPrefix: akash
      hdPath: m/44'/118'/0'/0/0

    - nodeset: terra
      faucet: terra-faucet
      gasPrice:
        price: "0.01"
      accountPrefix: terra
      hdPath: m/44'/330'/0'/0/0

  paths:
    - sideA: cosmos-hub
      sideB: akash

    - sideA: cosmos-hub
      sideB: terra

    - sideA: terra
      sideB: akash

