image: emeris/price-oracle-server:latest
imagePullPolicy: Always

replicas: 3

nodeSelector: {}

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

ports:
  http: 8000

databaseConnectionURL: postgres://root@cockroachdb:26257?sslmode=disable

debug: true

redisUrl: redis-master:6379
updateInterval: 10s