apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emeris
  namespace: emeris
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: cosmos-hub
            port:
              number: 1317
        path: /v1/liquidity(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: price-oracle
            port:
              number: 8000
        path: /v1/oracle(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: api-server
            port:
              number: 8000
        path: /v1(/|$)(.*)
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emeris-admin
  namespace: emeris
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: cns-server
            port:
              number: 8000
        path: /v1/cns(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: admin-ui
            port:
              number: 80
        path: /()(.*)
        pathType: ImplementationSpecific
