image: emeris/api-server:latest
imagePullPolicy: Always

replicas: 1

nodeSelector: {}

resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 4Gi

ports:
  http: 8000

cnsAddress: cns-server:8000

databaseConnectionURL: postgres://root@cockroachdb-public:26257?sslmode=disable

redisUrl: redis-master:6379