image: emeris/api-server:latest
imagePullPolicy: Always

replicas: 1

nodeSelector: {}

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 500m
    memory: 2Gi

ports:
  http: 8000

cnsAddress: cns-server:8000

databaseConnectionURL: postgres://root@cockroachdb:26257?sslmode=disable

redisUrl: redis-master:6379

debug: true

serviceMonitorLabels:
  release: monitoring-stack