image: emeris/api-server:latest
imagePullPolicy: Always

replicas: 3

nodeSelector: {}

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi

ports:
  http: 8000

cnsAddress: cns-server:8000

databaseConnectionURL: postgres://root@cockroachdb:26257?sslmode=disable

redisUrl: redis-master:6379

debug: true

serviceMonitorLabels:
  release: monitoring-stack