apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
type: Opaque
data:
  fixerKey: {{ .Values.fixerKey | b64enc }}