apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  ports:
{{- include "ports.service" . | indent 2 }}
  selector:
{{- include "chart.labels" . | indent 4 }}
