apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: akash
  namespace: emeris
spec:
  app:
    cliName: akash
    daemonName: akash
    name: akash
  init:
    chainID: akash-testnet
    bondDenom: uakt
    assets:
      - 100000000000000000uakt
    faucet:
      funds: 100000000000000000uakt
      denoms:
        - uakt
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      startupTimeout: 5m
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: akash
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: emeris/tracelistener-v42
        imagePullPolicy: Never
    reconcilePeriod: 1m
  image:
    name: gcr.io/tendermint-dev/akash
    version: v0.14.1
  moniker: emeris
  persistence:
    size: 10Gi
    autoResize:
      enabled: true
  replicas: 1
