apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: akash
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: akash
  app:
    cliName: akash
    daemonName: akash
    name: akash
  init:
    chainID: akash-testnet
    bondDenom: uakt
    assets:
      - 100000000000000000uakt
    faucet:
      funds: 100000000000000000uakt
      denoms:
        - uakt
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 20s
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0.018uakt
          - key: pruning
            value:
              string: custom
          - key: pruning-keep-recent
            value:
              string: "362880"
          - key: pruning-interval
            value:
              string: "100"
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: akash
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener:stable
        imagePullPolicy: Always
    reconcilePeriod: 5m
  image:
    name: ghcr.io/ovrclk/akash
    version: 0.14.1
  moniker: emeris
  persistence:
    size: 20Gi
    autoResize:
      enabled: true
  replicas: 1
