apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: cosmos-hub
  namespace: emeris
spec:
  app:
    name: gaia
    cliName: gaiad
    daemonName: gaiad
  init:
    chainID: cosmos-hub-testnet
    bondDenom: uatom
    assets:
      - 100000000000000000uatom
    faucet:
      funds: 100000000000000000uatom
      denoms:
        - uatom
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      startupTimeout: 5m
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: cosmos-hub
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: emeris/tracelistener44
        imagePullPolicy: Never
    reconcilePeriod: 1m
  image:
    name: gcr.io/tendermint-dev/gaia
    version: v6.0.0
    build:
      repository: https://github.com/cosmos/gaia
  moniker: emeris
  persistence:
    size: 10Gi
    autoResize:
      enabled: true
  replicas: 1
