apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: cosmos-hub
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: cosmos-hub
  app:
    name: gaia
    cliName: gaiad
    daemonName: gaiad
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 20s
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0.005uatom
          - key: pruning
            value:
              string: custom
          - key: pruning-keep-recent
            value:
              string: "362880"
          - key: pruning-interval
            value:
              string: "100"
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: cosmos-hub
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener44:stable
        imagePullPolicy: Always
    reconcilePeriod: 4m
  image:
    name: gcr.io/tendermint-dev/gaia
    version: v6.0.0
    build:
      repository: https://github.com/cosmos/gaia
  moniker: emeris
  persistence:
    size: 1100Gi
    storageClass: openebs-lvmpv
    autoResize:
      enabled: false
  replicas: 3
  resources:
    sentry:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi
