apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: akash
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: akash
  app:
    cliName: akash
    daemonName: akash
    name: akash
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 20s
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0.018uakt
          - key: pruning
            value:
              string: custom
          - key: pruning-keep-recent
            value:
              string: "362880"
          - key: pruning-interval
            value:
              string: "100"
          - group: api
            key: enabled-unsafe-cors
            value:
              bool: true
        config:
          - group: rpc
            key: cors_allowed_origins
            value:
              stringList:
              - '*'  
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: akash
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener-v42:1.2.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: ghcr.io/ovrclk/akash
    version: 0.14.1
  join:
    genesis:
      url: https://raw.githubusercontent.com/ovrclk/net/master/mainnet/genesis.json
    seeds:
      - address: 35.247.65.183
        id: 27eb432ccd5e895c5c659659120d68b393dd8c60
        port: 26656
      - address: 46.101.176.149
        id: 8e2f56098f182ffe2f6fb09280bafe13c63eb42f
        port: 26656
      - address: 46.166.138.218
        id: fff99a2e8f3c9473e4e5ee9a99611a2e599529fd
        port: 26656
    persistentPeers:
      - address: 35.247.65.183
        id: 27eb432ccd5e895c5c659659120d68b393dd8c60
      - address: 161.35.239.0
        id: 9180b99a5be3443677e0f57fc5f40e8f071bdcd8
        port: 51656
      - address: 142.93.77.25
        id: 47c9acc0e7d9b244a6404458e76d50b6284bfbbb
      - address: 3.235.249.94
        id: ab7b55588ea3f4f7a477e852aa262959e54117cd
      - address: 50.18.31.225
        id: 4acf579e2744268f834c713e894850995bbf0ffa
      - address: 54.219.88.246
        id: 3691ac1f56389ffec8579c13a6eb8eca41cf8ae3
      - address: 15.164.87.75
        id: 86afe23f116ba4754a19819a55d153008eb74b48
      - address: 138.201.159.100
        id: 6fbc3808f7d6c961e84944ae2d8c800a8bbffbb4
      - address: 165.22.69.102
        id: a2a3ffe7ac122a218e1f59c32a670f04b8fd3033
  moniker: emeris
  persistence:
    size: 100Gi
    autoResize:
      enabled: true
  replicas: 2
  resources:
    sentry:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi
