apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: desmos
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: desmos
  app:
    cliName: desmos
    daemonName: desmos
    name: desmos
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 15s
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0.001udsm
          - key: pruning
            value:
              string: custom
          - key: pruning-keep-recent
            value:
              string: "362880"
          - key: pruning-interval
            value:
              string: "100"
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: desmos
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener44:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: desmoslabs/desmos
    version: v2.3.1
  join:
    genesis:
      url: https://raw.githubusercontent.com/desmos-labs/mainnet/main/genesis.json
    seeds:
      - id: 9bde6ab4e0e00f721cc3f5b4b35f3a0e8979fab5
        address: seed-1.mainnet.desmos.network
        port: 26656
      - id: 5c86915026093f9a2f81e5910107cf14676b48fc
        address: seed-2.mainnet.desmos.network
        port: 26656
      - id: 45105c7241068904bdf5a32c86ee45979794637f
        address: seed-3.mainnet.desmos.network
        port: 26656
  moniker: emeris
  persistence:
    size: 200Gi
    autoResize:
      enabled: true
  replicas: 2
  resources:
    sentry:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 2Gi