apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: emoney
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: emoney
  app:
    cliName: emd
    daemonName: emd
    name: emoney
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 3m
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0.1ungm
          - key: pruning
            value:
              string: custom
          - key: pruning-keep-recent
            value:
              string: "362880"
          - key: pruning-interval
            value:
              string: "100"
          - group: api
            key: enabled-unsafe-cors
            value:
              bool: true
        config:
          - group: rpc
            key: cors_allowed_origins
            value:
              stringList:
              - '*' 
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: emoney
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener-v42:main
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: gcr.io/tendermint-dev/e-money
    version: v1.1.4
    build:
      repository: https://github.com/e-money/em-ledger
  join:
    genesis:
      url: https://raw.githubusercontent.com/e-money/networks/master/emoney-3/genesis.json
    persistentPeers:
      - id: 6420ef5087accdff4a87df5331d07da5de568743
        address: 18.194.208.47
        port: 28656
      - id: f49bf0e3d6d6057499ceb6613854af37a3da532a
        address: 3.121.126.177
        port: 28656
      - id: ecec8933d80da5fccda6bdd72befe7e064279fc1
        address: 207.180.213.123
        port: 26676
      - id: 0ad7bc7687112e212bac404670aa24cd6116d097
        address: 50.18.83.75
        port: 26656
      - id: 1723e34f45f54584f44d193ce9fd9c65271ca0b3
        address: 13.124.62.83
        port: 26656
      - id: 34eca4a9142bf9c087a987b572c114dad67a8cc5
        address: 172.105.148.191
        port: 26656
      - id: 0b186517e4d82eb4c000a567e486b7b96bf19752
        address: 44.195.95.22
        port: 26656
      - id: eed66085c975189e3d498fe61af2fcfb3da34924
        address: 217.79.184.40
        port: 26656
      - id: 226d713acb10a1cd09b3b890406b886d7b071cf2
        address: 10.105.2.101
        port: 26656
      - id: 552cb87c40f879c8c41005eeb36030502671e7a4
        address: 18.156.91.213
        port: 26656
      - id: 170255a4a9b120786d2d6c3931ebf0125087cca0
        address: 62.171.171.139
        port: 26656
      - id: d12ac664ff9766e0535c836173111e3eed462e79
        address: 185.144.83.157
        port: 26656
  moniker: emeris
  persistence:
    size: 200Gi
    autoResize:
      enabled: true
  replicas: 2
  resources:
    sentry:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi
