apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: juno
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: juno
  app:
    cliName: junod
    daemonName: junod
    name: juno
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 15s
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0.5ujuno
          - key: pruning
            value:
              string: custom
          - key: pruning-keep-recent
            value:
              string: "362880"
          - key: pruning-interval
            value:
              string: "100"
          - group: api
            key: enabled-unsafe-cors
            value:
              bool: true
        config:
          - group: rpc
            key: cors_allowed_origins
            value:
              stringList:
              - '*' 
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: juno
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener-v44:1.2.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: ghcr.io/cosmoscontracts/juno
    version: v2.1.0
  join:
    genesis:
      url: https://raw.githubusercontent.com/CosmosContracts/mainnet/main/juno-1/genesis.json
    seeds:
    - id: 2484353dab0b2c1275765b8ffa2c50b3b36158ca
      address: seed-node.junochain.com
    - id: ef2315d81caa27e4b0fd0f267d301569ee958893
      address: juno-seed.blockpane.com
  moniker: emeris
  persistence:
    size: 200Gi
    autoResize:
      enabled: true
  replicas: 2
  resources:
    sentry:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi
  expose:
    domain: juno.chain.staging.demeris.io
    grpc: true
    rpc: true
    api: true
