apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: osmosis
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: osmosis
  app:
    cliName: osmosisd
    daemonName: osmosisd
    name: osmosis
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 15s
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0uosmo
          - key: pruning
            value:
              string: custom
          - key: pruning-keep-recent
            value:
              string: "362880"
          - key: pruning-interval
            value:
              string: "100"
        config:
          - group: rpc
            key: timeout_broadcast_tx_commit
            value:
              string: 600s
          - group: rpc
            key: max_body_bytes
            value:
              int: 10000000
          - group: rpc
            key: max_header_bytes
            value:
              int: 10485760
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: osmosis
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener-v44:1.2.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: gcr.io/tendermint-dev/osmosis
    version: v7.0.4
  join:
    genesis:
      url: https://storage.googleapis.com/emeris/genesis/osmosis-1.json
    persistentPeers:
      - id: 4a11e483b99b2d89ff1dad56bd9b96234ce627d0
        address: osmosis-relay-0.emeris.svc.cluster.local
        port: 26656
      - id: 2e3e3b7703a598024a2fb287587095bc4d14fe52
        address: 95.217.196.54
        port: 2000
      - id: 8f67a2fcdd7ade970b1983bf1697111d35dfdd6f
        address: 52.79.199.137
        port: 26656
      - id: 00c328a33578466c711874ec5ee7ada75951f99a
        address: 35.82.201.64
        port: 26656
      - id: cfb6f2d686014135d4a6034aa6645abd0020cac6
        address: 52.79.88.57
        port: 26656
      - id: 785bc83577e3980545bac051de8f57a9fd82695f
        address: 194.233.164.146
        port: 26656
      - id: 7024d1ca024d5e33e7dc1dcb5ed08349768220b9
        address: 134.122.42.20
        port: 26656
      - id: d326ad6dffa7763853982f334022944259b4e7f4
        address: 143.110.212.33
        port: 26656
      - id: 9faf468b90a3b2b85ffd88645a15b3715f68bb0b
        address: 195.201.122.100
        port: 26656
      - id: fda06dcebe2acd17857a6c9e9a7b365da3771ceb
        address: 52.206.252.176
        port: 26656
      - id: 8d9967d5f865c68f6fe2630c0f725b0363554e77
        address: 134.255.252.173
        port: 26656
      - id: 778fdedf6effe996f039f22901a3360bc838b52e
        address: 161.97.187.189
        port: 36657
      - id: 64d36f3a186a113c02db0cf7c588c7c85d946b5b
        address: 209.97.132.170
        port: 26656
      - id: 4d9ac3510d9f5cfc975a28eb2a7b8da866f7bc47
        address: 37.187.38.191
        port: 26656
      - id: 2115945f074ddb038de5d835e287fa03e32f0628
        address: 95.217.43.85
        port: 26656
      - id: bf2c480eff178d2647ba1adfeee8ced568fe752c
        address: 91.65.128.44
        port: 26656
      - id: 2f9c16151400d8516b0f58c030b3595be20b804c
        address: 37.120.245.167
        port: 26656
      - id: bada684070727cb3dda430bcc79b329e93399665
        address: 173.212.240.91
        port: 26656
      - id: 3fea02d121cb24503d5fbc53216a527257a9ab55
        address: 143.198.145.208
        port: 26656
      - id: e7916387e05acd53d1b8c0f842c13def365c7bb6
        address: 176.9.64.212
        port: 26666
      - id: 55eea69c21b46000c1594d8b4a448563b075d9e3
        address: 34.107.19.235
        port: 26656
      - id: 7b6689cb18d625bbc069aa99d9d5521293db442c
        address: 51.158.97.192
        port: 26656
      - id: 2333a9288ec5f2b89e84fb802e2119dd367dfc05
        address: 51.77.117.110
        port: 2000
      - id: a0bd525884516148837e18c48887b4bc89017554
        address: 142.93.100.187
        port: 26656
      - id: d518832e4ded0484183fef3509d9f23ebb70b528
        address: 46.101.202.54
        port: 26656
      - id: ffc82412c0261a94df122b9cc0ce1de81da5246b
        address: 15.222.240.16
        port: 26656
      - id: 5b90a530464885fd28c31f698c81694d0b4a1982
        address: 35.183.238.70
        port: 26656
    seeds:
      - address: 95.217.196.54
        id: 085f62d67bbf9c501e8ac84d4533440a1eef6c45
        port: 26656
      - address: 162.55.132.230
        id: 63aba59a7da5197c0fbcdc13e760d7561791dca8
        port: 2000
      - address: osmosis.blockpane.com
        id: f515a8599b40f0e84dfad935ba414674ab11a668
        port: 26656
      - address: osmosis.artifact-staking.io
        id: 6bcdbcfd5d2c6ba58460f10dbcfde58278212833
        port: 26656
  moniker: emeris
  persistence:
    size: 1800Gi
    autoResize:
      enabled: true
  replicas: 4
  resources:
    sentry:
      limits:
        cpu: "4"
        memory: 16Gi
      requests:
        cpu: "2"
        memory: 8Gi
