apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: secret
  namespace: emeris
spec:
  app:
    cliName: secretcli
    daemonName: secretcli
    name: secret
  image:
    imagePullPolicy: Always
    name: enigmampc/secret-network-node
    version: v1.2.0-mainnet
  join:
    genesis:
      url: https://github.com/scrtlabs/SecretNetwork/releases/download/v1.2.0/genesis.json
    persistentPeers:
    - address: peer.node.scrtlabs.com
      id: 971911193b09a17c347565d311a3cc4f6004156d
      port: 26656
    - address: bootstrap.scrt.network
      id: 7649dcfda0eb77b38fde8e817da8071faea3cd13
      port: 26656
  moniker: emeris
  persistence:
    size: 100Gi
    autoResize:
      enabled: true
  replicas: 2
  resources:
    restServer: {}
    sentry: {}
    validator: {}
  sdkVersion: stargate
