apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: sentinel
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: sentinel
  app:
    cliName: sentinelhub
    daemonName: sentinelhub
    name: sentinel
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 30s
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0.05udvpn
          - key: pruning
            value:
              string: custom
          - key: pruning-keep-recent
            value:
              string: "362880"
          - key: pruning-interval
            value:
              string: "100"
          - group: api
            key: enabled-unsafe-cors
            value:
              bool: true
        config:
          - group: rpc
            key: cors_allowed_origins
            value:
              stringList:
              - '*' 
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: sentinel
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener-v42:1.2.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: gcr.io/tendermint-dev/sentinel
    version: v0.9.2
    build:
      repository: https://github.com/sentinel-official/hub
  join:
    genesis:
      url: https://storage.googleapis.com/emeris/genesis/sentinehub-2.json
    seeds:
      - address: 85.222.234.135
        id: 05fe2a7847fd27345250915fd06752c424f40651
        port: 26656
      - address: 54.176.90.228
        id: 387027e3b1180d3a619cbbf3462704a490785963
        port: 26656
      - address: 3.239.11.246
        id: 855807cc6a919c22ec943050ebb5c80b23724ed0
        port: 26656
      - address: 161.97.149.223
        id: d1efceccb04ded9a604e5235f76da86872157d68
        port: 26656
  moniker: emeris
  persistence:
    size: 100Gi
    autoResize:
      enabled: true
  replicas: 2
  resources:
    sentry:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi
  expose:
    domain: sentinel.chain.staging.demeris.io
    grpc: true
    rpc: true
    api: true
