apiVersion: apps.starport.cloud/v1
kind: NodeSet
metadata:
  name: starname
  namespace: emeris
spec:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              nodeset: starname
  app:
    cliName: starnamed
    daemonName: starnamed
    name: starname
  config:
    additionalEgressRules:
      - ports:
          - port: 26257
            protocol: TCP
    nodes:
      blockThreshold: 15s
      configOverride:
        app:
          - key: minimum-gas-prices
            value:
              string: 0.5uiov
          - key: pruning
            value:
              string: default
          - key: pruning-keep-recent
            value:
              string: "0"
          - key: pruning-interval
            value:
              string: "0"
          - group: api
            key: enabled-unsafe-cors
            value:
              bool: true
        config:
          - group: rpc
            key: cors_allowed_origins
            value:
              stringList:
              - '*' 
      startupTimeout: 1h
      traceStoreContainer:
        env:
          - name: TRACELISTENER_FIFOPATH
            value: /trace-store/kvstore.fifo
          - name: TRACELISTENER_DATABASECONNECTIONURL
            value: postgres://root@cockroachdb-public:26257?sslmode=disable
          - name: TRACELISTENER_TYPE
            value: gaia
          - name: TRACELISTENER_CHAINNAME
            value: starname
          - name: TRACELISTENER_DEBUG
            value: "true"
        image: gcr.io/tendermint-dev/emeris-tracelistener-v42:v1.3.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    reconcilePeriod: 5m
  image:
    name: iov1/starnamed
    version: v0.10.18
  join:
    genesis:
      url: https://gist.githubusercontent.com/davepuchyr/6bea7bf369064d118195e9b15ea08a0f/raw/genesis.json
    seeds:
      - address: 167.99.194.126
        id: ca133187b37b59d2454812cfcf31b6211395adec
        port: 26656
      - address: 13.37.85.253
        id: 1c7e014b65f7a3ea2cf48bffce78f5cbcad2a0b7
        port: 26656
      - address: 13.37.61.32
        id: 8c64a2127cc07d4570756b61f83af60d34258398
        port: 26656
      - address: 3.37.140.5
        id: 9aabe0ac122f3104d8fc098e19c66714c6f1ace9
        port: 26656
      - address: 35.247.175.128
        id: 94ac1c02b4e2ca3fb2706c91a68b8030ed3615a1
        port: 26656
      - address: 52.52.89.64
        id: be2235996b1c785a9f57eed25fd673ca111f0bae
        port: 26656
      - address: 212.71.247.11
        id: f63d15ab7ed55dc75f332d0b0d2b01d529d5cbcd
        port: 26656
      - address: 138.201.20.147
        id: f5597a7ed33bc99eb6ba7253eb8ac76af27b4c6d
        port: 26656
  moniker: emeris
  persistence:
    size: 150Gi
    autoResize:
      enabled: true
  replicas: 2
  resources:
    sentry:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 2Gi
  expose:
    domain: starname.chain.staging.emeris.com
    grpc: true
    rpc: true
    api: true
