image: emeris/ticket-watcher:latest
imagePullPolicy: Always

replicas: 1

nodeSelector: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

debug: false

redisUrl: redis-master:6379