apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emeris
  namespace: emeris
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: dev.demeris.io
    http:
      paths:
      - backend:
          service:
            name: cosmos-hub
            port:
              number: 1317
        path: /v1/liquidity(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: terra-fcd
            port:
              number: 3060
        path: /v1/services/terra/fcd(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: price-oracle
            port:
              number: 8000
        path: /v1/oracle(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: dexinfo
            port:
              number: 8080
        path: /v1/dexinfo(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: cns-server
            port:
              number: 8000
        path: /v1/cns(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: api-server
            port:
              number: 8000
        path: /v1(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - dev.demeris.io
    secretName: emeris-cert
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  use-gzip: true
  gzip-level: 1
  gzip-min-length: 128
