name: Check chain release versions on Emeris Staging Cluster

on:
  schedule:
    # Runs "At minute 0 past every 12th hour." (see https://crontab.guru)
    - cron: '0 */12 * * *'

jobs:
  check-version: 
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .github/workflows/scripts
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         export KUBECONFIG='${{ secrets.KUBECONFIG_STAGING }}'
         chmod +x ./check_latest_version.sh
         ./check_latest_version.sh
      shell: bash
