name: Deploy new Emeris backend stack image on dev

# This action is executed only via GitHub API call.
# All Emeris repositories call this action when their
# Docker image finished building, and they want it to be
# deployed on Dev environment.

# It works through repository_dispatch, the only type accepted is "dev-push".

# Since we use Helm to do deployments, for each image we need:
#  - new image SHA, `image_sha`
#  - image name, `image_name`
#  - service name, `service_name`
#  - repository url, embedded in payload response from GitHub webhook

on:
  repository_dispatch:
    types: [dev-push-*]

jobs:
  deploy-service:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TENDERBOT_GIT_TOKEN }}
          repository: "allinbits/${{ github.event.client_payload.repo_name }}"
          ref: ${{ github.event.client_payload.branch_name }}

      - name: Deploy
        if: ${{ github.event.client_payload.service_name != 'cns-server' }}
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          exec: |
            helm upgrade "${{ github.event.client_payload.service_name }}"  \
              --install \
              --namespace emeris \
              --set debug=true \
              --set fixerKey=${{ secrets.FIXER_KEY }} \
              --set cnsAddress=https://dev.demeris.io/v1/cns \
              --set image=gcr.io/tendermint-dev/"${{ github.event.client_payload.image_name }}":"${{ github.event.client_payload.image_sha }}" \
              ./helm

      - name: Deploy - CNS Server
        if: ${{ github.event.client_payload.service_name == 'cns-server' }}
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          exec: |
            helm upgrade "${{ github.event.client_payload.service_name }}"  \
              --install \
              --namespace emeris \
              --set debug=true \
              --set fixerKey=${{ secrets.FIXER_KEY }} \
              --set cnsAddress=https://dev.demeris.io/v1/cns \
              --set image=gcr.io/tendermint-dev/emeris-cns-server:"${{ github.event.client_payload.image_sha }}" \
              ./helm/cns-server

      - name: Deploy - Admin UI
        if: ${{ github.event.client_payload.service_name == 'cns-server' }}
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          exec: |
            helm upgrade "${{ github.event.client_payload.service_name }}"  \
              --install \
              --namespace emeris \
              --set debug=true \
              --set fixerKey=${{ secrets.FIXER_KEY }} \
              --set cnsAddress=https://dev.demeris.io/v1/cns \
              --set image=gcr.io/tendermint-dev/emeris-admin-ui:"${{ github.event.client_payload.image_sha }}" \
              ./helm/admin-ui

  ingress:
    runs-on: self-hosted
    needs: deploy-service
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: apply -n emeris -f ci/dev/ingress.yaml
