name: Deploy on Emeris Dev Environment

on:
  workflow_run:
    workflows: ["Build docker images"]
    branches: [master]
    types: 
      - completed

jobs:
  redis:
    runs-on: self-hosted
    steps:
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm repo add bitnami https://charts.bitnami.com/bitnami;
            helm upgrade redis \
              --install \
              --namespace emeris \
              --set auth.enabled=false \
              --set auth.sentinel=false \
              --set architecture=standalone \
              bitnami/redis

  cockroachdb:
    runs-on: self-hosted
    steps:
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm repo add cockroachdb https://charts.cockroachdb.com;
            helm upgrade cockroachdb \
              --install \
              --namespace emeris \
              --set tls.enabled=false \
              --set statefulset.replicas=3 \
              cockroachdb/cockroachdb

  cns-server:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm upgrade cns-server \
              --install \
              --namespace emeris \
              --set image=gcr.io/tendermint-dev/emeris-cns-server:${{ github.sha }} \
              ./helm/emeris-cns-server
  
  api-server:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm upgrade api-server \
              --install \
              --namespace emeris \
              --set image=gcr.io/tendermint-dev/emeris-api-server:${{ github.sha }} \
              ./helm/emeris-api-server

  rpcwatcher:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm upgrade rpcwatcher \
              --install \
              --namespace emeris \
              --set image=gcr.io/tendermint-dev/emeris-rpcwatcher:${{ github.sha }} \
              ./helm/emeris-rpcwatcher

  price-oracle:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm upgrade price-oracle \
              --install \
              --namespace emeris \
              --set image=gcr.io/tendermint-dev/emeris-price-oracle:${{ github.sha }} \
              --set fixerKey=${{ secrets.FIXER_KEY }} \
              ./helm/emeris-price-oracle-server

  admin-ui:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm upgrade admin-ui \
              --install \
              --namespace emeris \
              --set image=gcr.io/tendermint-dev/emeris-admin-ui:${{ github.sha }} \
              --set cnsAddress=https://dev.demeris.io/v1/cns \
              ./helm/emeris-admin-ui

  ingress:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: apply -n emeris -f ci/dev/ingress.yaml