name: Deploy Chains

on: 
  workflow_dispatch:
    inputs:
      cosmos-hub:
        description: 'Deploy Cosmos Hub'     
        required: true
        default: 'false'

jobs:
  cosmos-hub:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: wei/curl@v1
        with:
          args: -X POST -u tendermint:${{ secrets.DEV_CNS_PASSWORD }} -d @ci/dev/chains/cosmos-hub.json https://dev.demeris.io/v1/cns/add
