name: Deploy image

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Env to deploy to (dev/staging/prod)'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      service_name:
        description: 'Service name (e.g. api-server)'
        required: true
      image_tag:
        description: 'Docker image tag'
        required: true
      repo_name:
        description: 'Github repo name (e.g. demeris-api-server, defaults to $service_name)'
        required: false
      branch_name:
        description: 'Github branch to checkout (e.g. main)'
        required: true
        default: main
      image_name:
        description: 'Docker image name (e.g. emeris-api-server, defaults to emeris-$service_name)'
        required: false
      captcha:
        description: 'If you are updating prod, double check what you are doing and type "YES" (uppercase) here'
        required: false

env:
  env: ${{ github.event.inputs.env }}
  service_name: ${{ github.event.inputs.service_name }}
  repo_name: ${{ github.event.inputs.repo_name || github.event.inputs.service_name }}
  branch_name: ${{ github.event.inputs.branch_name }}
  image_name: ${{ github.event.inputs.image_name || format('{0}-{1}', 'emeris', github.event.inputs.service_name) }}
  image_tag: ${{ github.event.inputs.image_tag }}
  captcha: ${{ github.event.inputs.captcha }}

jobs:
  deploy-service:
    runs-on: self-hosted
    steps:
      - name: Check captcha
        if: env.env == 'prod'
        run: |
          if [[ $captcha == 'YES' ]]; then
              echo "captcha filled in correctly"
          else
              echo "wrong captcha"
              exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TENDERBOT_GIT_TOKEN }}
          repository: "EmerisHQ/${{ env.repo_name }}"
          ref: ${{ env.branch_name }}

      - name: Setup variables [dev]
        if: env.env == 'dev'
        run: |
          echo "KUBECONFIG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.KUBECONFIG }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "DEBUG=true" >> $GITHUB_ENV
          echo "API_BASE_URL=https://api.dev.emeris.com" >> $GITHUB_ENV
          echo "CNS_OAUTH_URL=https://admin.dev.emeris.com/login" >> $GITHUB_ENV

      - name: Setup variables [staging]
        if: env.env == 'staging'
        run: |
          echo "KUBECONFIG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.KUBECONFIG_STAGING }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "DEBUG=true" >> $GITHUB_ENV
          echo "API_BASE_URL=https://api.staging.emeris.com" >> $GITHUB_ENV
          echo "CNS_OAUTH_URL=https://admin.staging.emeris.com/login" >> $GITHUB_ENV

      - name: Setup variables [prod]
        if: env.env == 'prod'
        run: |
          echo "KUBECONFIG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.KUBECONFIG_PROD }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "DEBUG=false" >> $GITHUB_ENV
          echo "API_BASE_URL=https://api.emeris.com" >> $GITHUB_ENV
          echo "CNS_OAUTH_URL=https://admin.emeris.com/login" >> $GITHUB_ENV

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: "${{ env.KUBECONFIG_CONTENT }}"
          exec: |
            helm upgrade "${{ env.service_name }}"  \
              --install \
              --namespace emeris \
              --set debug=${{ env.DEBUG }} \
              --set fixerKey=${{ secrets.FIXER_KEY }} \
              --set image=gcr.io/tendermint-dev/"${{ env.image_name }}":"${{ env.image_tag }}" \
              --set daggregationPublicBaseUrl=${{ env.API_BASE_URL }}/v1/daggregation \
              --set dexInfoSwapsUrl=${{ env.API_BASE_URL }}/v1/dexinfo/swaps \
              --set redirectURL=${{ env.CNS_OAUTH_URL }} \
              --set test=true \
              ./helm

      - name: Send slack message
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": "[${{ env.env }}] new image deployed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "[${{ env.env }}] Deployed ${{ env.service_name }} version ${{ env.image_tag }}"
                  }
                }  
              ]
            }
        env:
          SLACK_WEBHOOK_URL:  ${{ secrets.SLACK_BACKEND_GHN }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK