name: Deploy new Emeris backend stack image on dev

# This action is executed only via GitHub API call.
# All Emeris repositories call this action when their
# Docker image finished building, and they want it to be
# deployed on Dev environment.

# It works through repository_dispatch, the only type accepted is "dev-push".

# Since we use Helm to do deployments, for each image we need:
#  - new image SHA, `image_sha`
#  - image name, `image_name`
#  - service name, `service_name`
#  - repository url, embedded in payload response from GitHub webhook

on:
  repository_dispatch:
    types: [dev-push-*]

concurrency:
  group: ${{ github.event.client_payload.deploy_type }}
  cancel-in-progress: false

jobs:
  deploy-service:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TENDERBOT_GIT_TOKEN }}
          repository: "allinbits/${{ github.event.client_payload.repo_name }}"
          ref: ${{ github.event.client_payload.branch_name }}

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          exec: |
            helm upgrade "${{ github.event.client_payload.service_name }}"  \
              --install \
              --namespace emeris \
              --set debug=true \
              --set fixerKey=${{ secrets.FIXER_KEY }} \
              --set image=gcr.io/tendermint-dev/"${{ github.event.client_payload.image_name }}":"${{ github.event.client_payload.image_sha }}" \
              --set daggregationPublicBaseUrl=https://dev.demeris.io/v1/daggregation \
              --set redirectURL=https://develop--emeris-admin.netlify.app/login \
              --set test=true \
              ./helm
  
  ingress:
    runs-on: self-hosted
    needs: deploy-service
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: apply -n emeris -f ci/dev/ingress.yaml

  emit-integration-test:
    if: ${{ github.event.client_payload.deploy_type == 'deploy_dev' }}
    runs-on: self-hosted
    needs: deploy-service
    steps:
      - name: Emit integration-test event on demeris-backend
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TENDERBOT_GIT_TOKEN }}
          repository: allinbits/demeris-backend
          event-type: integration-test
          client-payload: '{"env":"dev","service_name":"${{ github.event.client_payload.service_name }}","image_sha":"${{ github.event.client_payload.image_sha }}"}'
