name: Deploy Chains

on: 
  workflow_dispatch:
    inputs:
      cosmos_hub:
        description: 'Deploy Cosmos Hub'     
        required: true
        default: 'false'
      akash:
        description: 'Deploy Akash'     
        required: true
        default: 'false'
      crypto_com:
        description: 'Deploy Crypto.com'     
        required: true
        default: 'false'

jobs:
  cosmos-hub:
    if: ${{ github.event.inputs.cosmos_hub == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: wei/curl@v1
        with:
          args: -X POST -u tendermint:${{ secrets.DEV_CNS_PASSWORD }} -d @ci/dev/chains/cosmos-hub.json https://dev.demeris.io/v1/cns/add

      - name: Patch Chain
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: patch -n emeris nodeset cosmos-hub --patch "$(cat ci/dev/chains/cosmos-hub-patch.yaml)"

  akash:
    if: ${{ github.event.inputs.akash == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: wei/curl@v1
        with:
          args: -X POST -u tendermint:${{ secrets.DEV_CNS_PASSWORD }} -d @ci/dev/chains/akash.json https://dev.demeris.io/v1/cns/add

      - name: Patch Chain
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: patch -n emeris nodeset akash--patch "$(cat ci/dev/chains/akash-patch.yaml)"

  crypto-com:
    if: ${{ github.event.inputs.crypto_com == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: wei/curl@v1
        with:
          args: -X POST -u tendermint:${{ secrets.DEV_CNS_PASSWORD }} -d @ci/dev/chains/cryptocom.json https://dev.demeris.io/v1/cns/add

      - name: Patch Chain
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: patch -n emeris nodeset crypto-com --patch "$(cat ci/dev/chains/cryptocom-patch.yaml)"
