name: Integration tests

on:
  repository_dispatch:
    types: [integration-test]

env:
  GOPRIVATE: "github.com/allinbits/*"

jobs:
  tests:
    name: integration-tests
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Configure git for private modules
        env:
          GIT_TOKEN: ${{ secrets.TENDERBOT_GIT_TOKEN }}
        run: git config --global url."https://git:${GIT_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Run tests
        run: go test -v ./tests/...
        env:
          ENV: ${{ github.event.client_payload.env }}
          TESTS_WORKDIR: ${{ github.workspace }}

      - name: Emit test-pass event on demeris-backend
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TENDERBOT_GIT_TOKEN }}
          repository: allinbits/demeris-backend
          event-type: test-pass
          client-payload: '{"env":"${{ github.event.client_payload.env }}","service_name":"${{ github.event.client_payload.service_name }}","image_sha":"${{ github.event.client_payload.image_sha }}"}'

  test-e2e:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run e2e tests
        run: make staging-int-tests
        shell: bash
        env:
          ENV: 'staging'
          KUBECONFIG: '${{ secrets.KUBECONFIG_STAGING }}'
