name: golangci-lint
on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - sahith/update-dev
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
env:
  GOPRIVATE: "github.com/allinbits/*"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Configure git for private modules
        env:
          GIT_TOKEN: ${{ secrets.TENDERBOT_GIT_TOKEN }}
        run: git config --global url."https://git:${GIT_TOKEN}@github.com".insteadOf "https://github.com"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.43
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
