name: Lint
on:
  push:
    branches:
      - master
      - develop
      - sahith/update-dev
  pull_request:
    branches:
      - master
      - develop
      - sahith/update-dev
jobs:
  golangci:
  name: lint
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2