name: golangci-lint
on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
env:
  GOPRIVATE: "github.com/emerishq,github.com/allinbits"

jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Configure git for private modules
        env:
          GIT_TOKEN: ${{ secrets.TENDERBOT_GIT_TOKEN }}
        run: git config --global url."https://git:${GIT_TOKEN}@github.com".insteadOf "https://github.com"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.44
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
