name: Reset Emeris Dev Environment

on: 
  workflow_dispatch:
    inputs:
      delete_nodesets:
        description: 'Whether to also delete NodeSet resources'     
        required: true
        default: 'false'
      delete_faucets:
        description: 'Whether to also delete Faucet resources'     
        required: true
        default: 'false'
      delete_relayers:
        description: 'Whether to also delete Relayer resources'     
        required: true
        default: 'false'

jobs:
  redis:
    runs-on: self-hosted
    steps:
      - name: Uninstall
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: helm uninstall redis --namespace emeris

  cockroachdb:
    runs-on: self-hosted
    steps:
      - name: Uninstall
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: helm uninstall cockroachdb --namespace emeris

  cns-server:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Uninstall
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: helm uninstall cns-server --namespace emeris
  
  api-server:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Uninstall
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: helm uninstall api-server --namespace emeris

  rpcwatcher:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Uninstall
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: helm uninstall rpcwatcher --namespace emeris

  price-oracle:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Uninstall
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: |
            helm uninstall price-oracle --namespace emeris

  admin-ui:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Uninstall
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: helm uninstall admin-ui --namespace emeris

  ingress:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: delete --namespace emeris -f ci/ingress.yaml

  pvcs:
    runs-on: self-hosted
    steps:
      - name: Delete
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: delete --all pvc --namespace emeris

  nodesets:
    if: ${{ github.event.inputs.delete_nodesets == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Delete
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: delete --all nodesets --namespace emeris

  faucets:
    if: ${{ github.event.inputs.delete_faucets == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Delete
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: delete --all faucets --namespace emeris

  relayers:
    if: ${{ github.event.inputs.delete_relayers == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Delete
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBECONFIG_B64 }}
          command: delete --all relayers --namespace emeris
