image: emeris/admin-ui:latest
imagePullPolicy: Always

replicas: 1

nodeSelector: {}

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 250m
    memory: 500Mi

ports:
  http: 80